In [1]:
import duckdb
import pandas as pd

## Baloto

In [2]:
path = r'/home/sebas/Documents/projects/opensource/subagents/finance_agent/resources/Amazon 2_Raw.xlsx'

In [5]:
df = pd.read_excel(path)
df.head()

,Order ID,Order Date,Ship Date,EmailID,Geography,Category,Product Name,Sales,Quantity,Profit
0,CA-2013-138688,2013-06-13,2013-06-17,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,6.8714
1,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,14.1694
2,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,Newell 322,7.280,4,1.9656
3,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,Mitel 5320 IP Phone VoIP phone,907.152,4,90.7152
4,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,5.7825

In [6]:
results = duckdb.sql("SELECT * FROM df").df()
results.tail()

,Order ID,Order Date,Ship Date,EmailID,Geography,Category,Product Name,Sales,Quantity,Profit
3198,CA-2013-125794,2013-09-30,2013-10-04,MarisLaWare@gmail.com,"United States,Los Angeles,California",Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,15.2208
3199,CA-2014-121258,2014-02-27,2014-03-04,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,15.6332
3200,CA-2014-121258,2014-02-27,2014-03-04,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Phones,Aastra 57i VoIP phone,258.576,2,19.3932
3201,CA-2014-121258,2014-02-27,2014-03-04,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,13.3200
3202,CA-2014-119914,2014-05-05,2014-05-10,ChrisCortes@gmail.com,"United States,Westminster,California",Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,72.9480

In [8]:
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      3203 non-null   str
 1   Order Date    3203 non-null   datetime64[us]
 2   Ship Date     3203 non-null   datetime64[us]
 3   EmailID       3203 non-null   str
 4   Geography     3203 non-null   str
 5   Category      3203 non-null   str
 6   Product Name  3203 non-null   str
 7   Sales         3203 non-null   float64
 8   Quantity      3203 non-null   int64
 9   Profit        3203 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(1), str(5)
memory usage: 250.4 KB

Suma de la columna C1

In [10]:
query = '''
SELECT SUM(Sales) 
FROM results
WHERE EmailID >= 'MarisLaWare@gmail.com'
'''

duckdb.sql(query)

┌────────────────────┐
│     sum(Sales)     │
│       double       │
├────────────────────┤
│ 270936.86899999995 │
└────────────────────┘